### ISSUE TITLE
Exception in reset_json function in Dashboard/objects/Table.py

### ISSUE THREAD

**Issue by jovanrajsic** [ECC-BFMC/Computer#2]
When running Dashboard app there is an exception and the program aborts:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\jrajsic\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\jrajsic\Documents\bfmc\Computer\Dashboard\GUI\GUI_start.py", line 122, in run
    dashBoard.draw()
  File "C:\Users\jrajsic\Documents\bfmc\Computer\Dashboard\GUI\DashBoard.py", line 268, in draw
    object.draw()
  File "C:\Users\jrajsic\Documents\bfmc\Computer\Dashboard\objects\Table.py", line 407, in draw
    for index, e in enumerate(self.valuesFromPi.keys()):
AttributeError: 'set' object has no attribute 'keys'
```
In reset_json function in Dashboard/objects/Table.py there is an assignment which converts dict to set in line 597 :
`self.valuesFromPi = {+ len(self.dataEnums) + len(self.dataRange)}`
I do not understand the semantics of this line. I changed the line to:
`self.valuesFromPi = {}`
and Dashboard works fine.

**Comment by Eleches-max** [comment]
Hello! Did you manage to solve the error?

**Comment by jovanrajsic** [comment]
As I said i changed the line to `self.valuesFromPi = {}` and the error was solved.

**Comment by Eleches-max** [comment]
The interface opens, but it doesn't connect to the server. The port and IP are set correctly.

**Comment by jovanrajsic** [comment]
Did you launch the Brain app on RPi?

**Comment by Eleches-max** [comment]
yes

**Comment by jovanrajsic** [comment]
Maybe the port number is wrong. Anyways, it would be better to open a topic on the forum, your problem is not related to this issue.
